baseURL = 'https://cadforone.com/'
title = 'CAD For One - Mechanical Design Tutorials'
theme = 'hextra'

# Markdown config
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

# Menu (top nav bar)
[menu]
  [[menu.main]]
    name = 'Tutorials'
    pageRef = '/docs'
    weight = 1
  [[menu.main]]
    name = 'Search'
    weight = 2
    [menu.main.params]
      type = 'search'

# Site params
[params]
  [params.navbar]
    displayTitle = true
    displayLogo = false
  [params.footer]
    displayCopyright = false
    displayPoweredBy = true
