# Decap CMS Configuration — Simple

backend:
  name: github
  repo: goxiaohub/cadforone
  branch: main

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'

site_url: https://cadforone.com

collections:
  - name: 'posts'
    label: 'Tutorials'
    folder: 'content/posts'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD', timeFormat: false }
      - { label: 'Description', name: 'description', widget: 'text', required: false }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
